version: 1.0.{build}
pull_requests:
  do_not_increment_build_number: true
skip_tags: true
image: Visual Studio 2019
build_script:
- cmd: CPP\appveyor.cmd
artifacts:
- path: '*.7z'
deploy:
- provider: GitHub
  auth_token:
    secure: iXetSwDw8Qmp/amb52HHsLLsTxgA+adSK+KQDJsnNFkm0GdhcxjJ9kEJQRfxiKMp
  draft: true