name: Build

on:
  push:
    #branches: [ "master" ]
  pull_request:
    #branches: [ "master" ]

env:
  PROJECT_NAME: 7-Zip-zstd
  VC: 17.0
  SUBSYS: 6.02
  
jobs:
  build:
    strategy:
      matrix:
        ARCH: [x86, x64, x64_arm, x64_arm64]
    runs-on: windows-latest

    steps:
      - uses: actions/setup-dotnet@v1
      - name: Set up Visual Studio shell
        uses: egor-tensin/vs-shell@v2

      - name: Generate Version
        id: versioning
        uses: sceccotti89/Github-Action-Versioning@v1.0.5
        
      - uses: actions/checkout@v3
      
      - name: Build
        working-directory: ${{env.GITHUB_WORKSPACE}}
        env:
          ARCH: ${{ matrix.ARCH }}
          BUILD_VERSION: ${{ steps.versioning.outputs.version }}
        run: CPP\GitHubActions.cmd
