name: Build

on:
  push:
    #branches: [ "master" ]
  pull_request:
    #branches: [ "master" ]

env:
  PROJECT_NAME: 7-Zip-zstd
  VC: 17.0
  SUBSYS: 6.02
  
jobs:
  build:
    strategy:
      matrix:
        ARCH: [x86, x64, x64_arm, x64_arm64]
    runs-on: windows-latest

    steps:
      - uses: actions/setup-dotnet@v1
      - name: Set up Visual Studio shell
        uses: egor-tensin/vs-shell@v2

      - name: Generate Version
        id: versioning
        uses: sceccotti89/Github-Action-Versioning@v1.0.5
        
      - uses: actions/checkout@v3

      - name: Cache
        uses: actions/cache@v3
        with:
          path: |
            "**/*.exp"
            "**/*.pch"
            "**/*.obj"
          key: ${{ runner.os }}-${{ matrix.ARCH }}-${{ env.VC }}

      - name: Build
        working-directory: ${{env.GITHUB_WORKSPACE}}
        env:
          ARCH: ${{ matrix.ARCH }}
          BUILD_VERSION: ${{ steps.versioning.outputs.version }}
        run: CPP\GitHubActions.cmd

      - uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.ARCH }}
          path: "*.7z"
  release:
    needs: build
    name: Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v3.0.0
      - name: Display structure of downloaded files
        run: ls -R
      - name: Release
        uses: softprops/action-gh-release@v1
        #if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            ./x86/*.7z
            ./x64/*.7z
            ./x64_arm/*.7z
            ./x64_arm64/*.7z
